version: "3.9"

services:
  backend:
    build: backend
    restart: always
    depends_on:
      - redis
      - postgres
    environment:
      APP_DATABASE__USERNAME: appcenter
      APP_DATABASE__PASSWORD: "${POSTGRES_PASSWORD}"
      APP_DATABASE__HOST: postgres
      APP_REDIS__URI: redis://redis
      APP_SECRET__SECRET_KEY: "${APP_SECRET_KEY}"
      APP_SECRET__HMAC_SECRET: "${APP_HMAC_SECRET}"

  frontend:
    build: frontend
    restart: always
    depends_on:
      - backend

  redis:
    image: "redis:7.0"
    restart: always

  postgres:
    image: "postgres:15.3"
    restart: always
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_USER: appcenter
      POSTGRES_DATABASE: appcenter_website
