application:
  port: 3100
  host: 127.0.0.1
  base_url: ""

secret:
  token_expiration: 30
  # Deliberately invalid base64
  secret_key: "!"
  hmac_secret: "!"

database:
  port: 5432
  host: ""
  database_name: "appcenter_website"
  username: ""
  password: ""
  require_ssl: false

github:
  client_id: ""
  client_secret: ""
  username: ""
  access_token: ""
  reviews_url: "https://github.com/elementary/appcenter-reviews.git"
  local_repo_path: "/tmp/appcenter-reviews"

email:
  host: "smtp.gmail.com"
  port: 25
  authentication: true
  host_user: ""
  host_user_password: ""

redis:
  uri: "redis://127.0.0.1"