application:
  port: 3100

database:
  port: 5432
  database_name: "appcenter_website"
  username: ""
  password: ""

github:
  client_id: ""
  client_secret: ""
  username: ""
  access_token: ""
  reviews_url: "https://github.com/elementary/appcenter-reviews.git"
  local_repo_path: "/tmp/appcenter-reviews"

email:
  host: "smtp.gmail.com"
  port: 25
  authentication: true
  host_user: ""
  host_user_password: ""

redis:
  uri: "redis://127.0.0.1"
  pool_max_open: 16
  pool_max_idle: 8
  pool_timeout_seconds: 1
  pool_expire_seconds: 60