application:
  host: 0.0.0.0
  base_url: ""

github:
  reviews_url: "https://github.com/elementary/appcenter-reviews.git"
  local_repo_path: "/tmp/appcenter-reviews"

frontend_url: "https://appcenter-beta.elementary.io"

debug: false