[package]
authors = ["David Hewitt <davidmhewitt@gmail.com"]
name = "backend"
version = "0.1.0"
edition = "2021"

[workspace]
members = [
    "crates/appstream-worker",
    "crates/git-worker",
]

[lib]
path = "src/lib.rs"

[[bin]]
path = "src/main.rs"
name = "backend"

[dependencies]
actix-files = "0.6.2"
actix-session = { version = "0.7.2", features = ["cookie-session"] }
actix-web = "4"
anyhow = "1.0.71"
appstream-worker = { path = "crates/appstream-worker" }
argon2 = "0.5.0"
chrono = { version = "0.4.24", features = ["serde"] }
config = { version = "0.13", features = ["yaml"] }
deadpool-redis = "0.12.0"
dotenv = "0.15"
git-worker = { path = "crates/git-worker" }
hex = "0.4.3"
lettre = { version = "0.10.4", features = ["builder", "tokio1-native-tls"] }
minijinja = { version = "0.32.1", features = ["source"] }
oauth2 = "4.3.0"
once_cell = "1.17.1"
pasetors = "0.6.6"
reqwest = { version = "0.11.17" }
secrecy = { version = "0.8.0", features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0.96", features = ["raw_value"] }
serde_variant = "0.1.2"
sqlstate = { version = "0.1.0", features = ["postgres"] }
sqlx = { version = "0.6.3", features = ["runtime-tokio-native-tls", "postgres", "uuid", "chrono", "migrate"] }
tokio = { version = "1.28", features = ["macros", "rt-multi-thread"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3.17", features = [
    "fmt",
    "std",
    "env-filter",
    "registry",
    'json',
    'tracing-log',
] }
url = "2.3.1"
uuid = { version = "1.3.1", features = ["v4", "serde"] }
