[package]
name = "github-utils"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.71"
common = { path = "../../common" }
octocrab = "0.23.0"
once_cell = "1.17.1"
secrecy = "0.8.0"
