[package]
name = "appstream-worker"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
appstream = { version = "0.2.2", features = ["gzip"] }
chrono = "0.4.24"
deadpool-redis = "0.12.0"
http-cache-reqwest = "0.9.0"
lenient_semver = { version = "0.4.2", features = ["semver"] }
reqwest = { version = "0.11.17", features = ["stream"] }
reqwest-middleware = "0.2.1"
semver = "1.0"
serde = { version = "1.0.160", features = ["derive"] }
serde_json = "1.0.96"
tokio = { version = "1.28.0", features = ["fs"] }
tokio-stream = "0.1.14"
tokio-util = { version = "0.7.8", features = ["io"] }
tracing = "0.1.37"
