version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    environment:
      - DATABASE_URL=postgresql://appcenter:appcenter@db/appcenter_website
      - APP_DATABASE__URL=postgresql://appcenter:appcenter@db/appcenter_website
      - APP_REDIS__URI=redis://redis

    volumes:
      - ..:/workspace:cached

    command: sleep infinity

  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: appcenter_website
      POSTGRES_USER: appcenter
      POSTGRES_PASSWORD: appcenter
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - 5432:5432

  redis:
    image: redis:latest
    restart: unless-stopped
    hostname: redis
    ports:
      - 6379:6739

  email:
    image: rnwood/smtp4dev
    restart: unless-stopped
    ports:
      - 2580:80

  stripe:
    image: stripe/stripe-mock:latest
    restart: unless-stopped
    ports:
      - 12111:12111

volumes:
  postgres-data: null