on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  push-backend:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v3

      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: 'Build Backend Container'
        run: |
          docker build backend --tag ghcr.io/${{github.actor}}/appcenter-website/backend:latest
          docker push ghcr.io/${{github.actor}}/backend:latest

  push-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v3

      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: 'Build Frontend Container'
        run: |
          docker build frontend --tag ghcr.io/${{github.actor}}/appcenter-website/frontend:latest
          docker push ghcr.io/${{github.actor}}/frontend:latest