on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  push-backend:
    concurrency: 
      group: backend-container
      cancel-in-progress: true
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: davidmhewitt
          password: ${{secrets.GITHUB_TOKEN}}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: backend
          push: true
          tags: ghcr.io/davidmhewitt/appcenter-website/backend:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

  push-frontend:
    concurrency: 
      group: frontend-container
      cancel-in-progress: true
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v4

      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: davidmhewitt
          password: ${{secrets.GITHUB_TOKEN}}

      - name: 'Build Frontend Container'
        run: |
          docker build frontend --tag ghcr.io/davidmhewitt/appcenter-website/frontend:latest
          docker push ghcr.io/davidmhewitt/appcenter-website/frontend:latest
