on:
  pull_request:
  push:
    branches: [main]

jobs:
  build:
    name: Rust build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install stable rust
        run: rustup toolchain install stable
      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: "backend"
      - name: Build
        run: cd backend && cargo build --all-features