on:
  pull_request:
  push:
    branches: [main]

jobs:
  build:
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_DB: appcenter_website
          POSTGRES_USER: appcenter
          POSTGRES_PASSWORD: appcenter
          POSTGRES_HOST_AUTH_METHOD: trust
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
      stripe:
        image: stripe/stripe-mock:latest
        ports:
          - 12111:12111

    name: Rust build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install stable rust
        run: rustup toolchain install stable
      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: "backend"
      - name: Build
        run: |
          git config --global init.defaultBranch main
          cd backend
          cargo build --workspace --all-features
      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@cargo-llvm-cov
      - name: Generate code coverage
        env:
          DATABASE_URL: postgresql://appcenter:appcenter@localhost/appcenter_website
          APP_DATABASE__URL: postgresql://appcenter:appcenter@localhost/appcenter_website
          STRIPE_MOCKS_URL: http://localhost:12111
        run: cd backend && cargo llvm-cov --all-features --workspace --lcov --output-path lcov.info
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
          files: backend/lcov.info