on:
  pull_request:
  push:
    branches: [main]

jobs:
  build:
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_DB: appcenter_website
          POSTGRES_USER: appcenter
          POSTGRES_PASSWORD: appcenter
          POSTGRES_HOST_AUTH_METHOD: trust
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    name: Rust build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install stable rust
        run: rustup toolchain install stable
      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: "backend"
      - name: Build
        env:
          DATABASE_URL: postgresql://appcenter:appcenter@localhost/appcenter_website
        run: |
          git config --global user.name "David Hewitt"
          git config --global user.email "davidmhewitt@gmail.com"
          git config --global init.defaultBranch main
          cd backend
          cargo build --workspace --all-features
          cargo test --workspace